AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Bot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Architectures:
        - x86_64
      Runtime: python3.10
      CodeUri: .
      Description: 'ForTest'
      MemorySize: 128
      Timeout: 120
